### ISSUE TITLE
[Bug]: gcc-default-9 is broken

### ISSUE THREAD

**Issue by 1q23lyc45** [termux-user-repository/tur#1284]
### Problem description

```
~ $ apt install gcc-default-10
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gcc-10 : Depends: ndk-sysroot-gcc-compact (< 27) but 27b-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### What steps will reproduce the bug?

```
~ $ apt install gcc-default-9
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gcc-9 : Depends: ndk-sysroot-gcc-compact (< 27) but 27b-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### System information

termux-info:

```

```

**Comment by licy183** [comment]
`gcc-8/9/10` is not maintained since NDK r27, as it lacks too many features required by libc++ headers. If you really want to use it, download `ndk-sysroot-gcc-compat=26b-7` manually and install it.

```
wget https://github.com/termux-user-repository/dists/releases/download/0.1/ndk-sysroot-gcc-compact_26b-7_aarch64.deb
apt install ./ndk-sysroot-gcc-compact_26b-7_aarch64.deb
apt install gcc-9
```

**Comment by 1q23lyc45** [comment]
> `gcc-8/9/10` is not maintained since NDK r27, as it lacks too many features required by libc++ headers. If you really want to use it, download `ndk-sysroot-gcc-compat=26b-7` manually and install it.
> 
> ```
> wget https://github.com/termux-user-repository/dists/releases/download/0.1/ndk-sysroot-gcc-compact_26b-7_aarch64.deb
> apt install ./ndk-sysroot-gcc-compact_26b-7_aarch64.deb
> apt install gcc-9
> ```

Why not pull out a separate ndk-sysroot-gcc-compat-26 and put it in tur-disabled?
Some programs must also use NDK26, and will get a segment error if forced to use NDK27.

**Comment by licy183** [comment]
> Why not pull out a separate ndk-sysroot-gcc-compat-26 and put it in tur-disabled?

Putting packages in `tur-disabled` will not help a lot, as it will not get uploaded to TUR's apt repo. Besides, `gcc-9/10` should have been removed from TUR's apt repo. But due to the imperfect functions of the CI system, it will not be removed automatically.

> Some programs must also use NDK26, and will get a segment error if forced to use NDK27.

If you use gcc from the TUR repository to compile a program, the program is not compiled with the compiler (clang) provided by the NDK, but only with the header files of libc++, because the default STL runtime on Termux is libc++. For users, there should be no big difference between using NDK 26 and header files and NDK 27 header files on Termux. If the segfault error happens, you can report it here and TUR patches lots of files of the NDK headers.
Besides, if you cross-compile it with the NDK on your computer and it really happens, either the program is written in a way that causes undefined behavior, or clang is over-optimizing. You should report it to the program source code repository or the NDK (and possibly even llvm-project).

**Comment by 1q23lyc45** [comment]
OK
